// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBRBnSZBdcT22VzYgLN4nHQqGObvNFaX4Y',
    appId: '1:985481696255:web:1ad5ca343d35ba66ce8dca',
    messagingSenderId: '985481696255',
    projectId: 'my-nbc',
    authDomain: 'my-nbc.firebaseapp.com',
    storageBucket: 'my-nbc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBqwrfnhZB0_ilgLKmxl9Un2rr6ynWOyFw',
    appId: '1:985481696255:android:5680d5553eed204bce8dca',
    messagingSenderId: '985481696255',
    projectId: 'my-nbc',
    storageBucket: 'my-nbc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBIqzDMM3Kk2AKd2NsoZv_c3xoag3Ejnww',
    appId: '1:985481696255:ios:bd3edc6fe08369afce8dca',
    messagingSenderId: '985481696255',
    projectId: 'my-nbc',
    storageBucket: 'my-nbc.appspot.com',
    iosBundleId: 'com.example.nbc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBIqzDMM3Kk2AKd2NsoZv_c3xoag3Ejnww',
    appId: '1:985481696255:ios:7d9204193875c7adce8dca',
    messagingSenderId: '985481696255',
    projectId: 'my-nbc',
    storageBucket: 'my-nbc.appspot.com',
    iosBundleId: 'com.example.nbc.RunnerTests',
  );
}
